config/routes.rb
Rails.application.routes.draw do

  root to: "sections#home"

  # get 'sections/home'

  # get 'menu/about'
  get 'about' => 'sections#about', as: :about

  get 'services' => 'sections#services', as: :services

  get 'portfolio' => 'sections#portfolio', as: :portfolio

  # get 'menu/contact'
  # get 'contact' => 'sections#contact', as: :contact

  get 'contact', to: 'messages#new', as: 'new_message'

  post 'contact', to: 'messages#create', as: 'create_message'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :subject, :body
  validates :name, :email, :subject, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end
  def create
    @message = Message.new message_params
    if @message.valid?
      MessageMailer.contact(@message).deliver_now
      redirect_to new_message_url
      flash[:notice] = "We have received your message and will be in touch soon!"
    else
      flash[:notice] = "There was an error sending your message. Please try again."
      render :new
    end
  end
  private
  def message_params
    params.require(:message).permit(:name, :email, :subject, :body)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def home
  end

  def about
  end

  def services
  end

  def portfolio
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_active?(link_path)
    current_page?(link_path) ? "active" : ""
  end
end

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<footer id="footer-container">

  <div id="footer" class="default-color">

    <!--<div class="container">-->
      <!--<div class="row">-->
        <!--<div class="col-sm-12">-->

          <!--<div class="widget widget-social">-->

            <!--<div class="social-media text-center">-->

              <!--<a class="pinterest" href="#"><i class="fa fa-pinterest"></i></a>-->
              <!--<a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a>-->
              <!--<a class="instagram" href="#"><i class="fa fa-instagram"></i></a>-->
              <!--<a class="facebook" href="#"><i class="fa fa-facebook"></i></a>-->
              <!--<a class="twitter" href="#"><i class="fa fa-twitter"></i></a>-->

            <!--</div>&lt;!&ndash; social-media &ndash;&gt;-->

          <!--</div>&lt;!&ndash; widget-social &ndash;&gt;-->

        <!--</div>&lt;!&ndash; col &ndash;&gt;-->
      <!--</div>&lt;!&ndash; row &ndash;&gt;-->
    </div><!-- container -->

  </div><!-- footer -->

  <div id="footer-bottom">

    <div class="container">
      <div class="row">
        <div class="col-sm-12">

          <div class="widget widget-text">

            <div class="text-center">

              <!--<img src="assets/images/footer-logo.png" alt="">-->
              <%= link_to(image_tag("logo/Logo_Coliman-01.png", :alt => "myway2", size: "80x80"), "/") %>

              <p><small>2017 &copy; All rights reserved</small></p>

            </div>

          </div><!-- widget-text -->

        </div><!-- col -->
      </div><!-- row -->
    </div><!-- container -->

  </div><!-- footer-bottom -->

</footer><!-- FOOTER CONTAINER -->

app/views/layouts/_navbar.html.erb
<!-- HEADER -->
<header id="header">

  <!-- HEADER TOP -->
  <div id="header-top">

    <div class="container">
      <div class="row">
        <div class="col-sm-12">

          <!-- LOGO -->
          <div id="logo">
            <a href="#">
              <%= link_to(image_tag("logo/Logo_Coliman-01.png", :alt => "myway2", size: "80x80"), root_path, :"data-no-turbolink" => true, method: "get") %>
            </a>
          </div><!-- LOGO -->

        </div><!-- col -->
      </div><!-- row -->
    </div><!-- container -->

  </div><!-- header-top -->

  <div class="container">
    <div class="row">
      <div class="col-sm-12">

        <!-- MENU -->
        <nav>

          <a id="mobile-menu-button" class="waves" href="#"><i class="halcyon-icon-menu"></i></a>

          <ul class="menu clearfix" id="menu">
            <li class="<%= is_active?(root_path) %>">
              <%= link_to "Home", root_path, :"data-no-turbolink" => true, method: "get" %>
            </li>
            <li class="<%= is_active?(about_path) %>">
              <%= link_to "About", about_path, :"data-no-turbolink" => true, method: "get" %>
            </li>
            <li class="<%= is_active?(services_path) %>">
              <%= link_to "Services", services_path, :"data-no-turbolink" => true, method: "get" %>
            </li>
            <li class="<%= is_active?(portfolio_path) %>">
              <%= link_to "Portfolio", portfolio_path, :"data-no-turbolink" => true, method: "get" %>
            </li>
            <li class="<%= is_active?(new_message_path) %>">
              <%= link_to "Contact", new_message_path, :"data-no-turbolink" => true, method: "get" %>
            </li>
          </ul>

        </nav>

      </div><!-- col -->
    </div><!-- row -->
  </div><!-- container -->

</header><!-- HEADER -->

app/views/layouts/application.html.erb
<!doctype html>
<html>

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0, shrink-to-fit=no">
  <meta name="keywords" content="">
  <meta name="description" content="">

  <title>Coliman</title>

  <!-- FAVICON AND APPLE TOUCH -->
  <!--<link rel="shortcut icon" href="favicon.png">-->
  <!--<link rel="apple-touch-icon" sizes="180x180" href="apple-touch-180x180.png">-->
  <!--<meta name="msapplication-TileImage" content="mstile.png">-->
  <!--<meta name="msapplication-TileColor" content="#7a00ff">-->
  <!--<meta name="theme-color" content="#7a00ff">-->

  <!-- FONTS -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i">

  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'plugins.css', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'animations/animate.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'fancybox/jquery.fancybox.css', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'custom-icons/css/custom-icons.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'custom-school-icons/css/custom-school-icons.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'custom-interface-icons/css/custom-interface-icons.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'custom-office-icons/css/custom-office-icons.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'revolutionslider/css/settings.css', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'revolutionslider/css/layers.css', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'revolutionslider/css/navigation.css', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'owl-carousel/owl.carousel.css', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body class="sticky-header header-style-2">

  <div id="main container">

      <%= render 'layouts/navbar' %>

      <%= yield %>

      <%= render 'layouts/footer' %>

  </div><!-- MAIN CONTAINER -->

  <!-- SCROLL UP -->
  <!--<a id="scroll-up" class="waves"><i class="fa fa-angle-up"></i></a>-->

</body>
</html>

app/views/messages/new.html.erb
<!-- PAGE CONTENT -->
<div id="page-content">

  <div id="page-header" class="parallax" data-stellar-background-ratio="0.1" style="background-image:url(<%= asset_path 'backgrounds/page-header-8.jpg' %>);">

    <div class="container">
      <div class="row">
        <div class="col-sm-12">

          <h1>Contact</h1>

          <ol class="breadcrumb">
            <li><a href="#">Home</a></li>
            <li class="active">Contact</li>
          </ol>

        </div><!-- col -->
      </div><!-- row -->
    </div><!-- container -->

  </div><!-- page-header -->

  <div class="container">
    <div class="row">
      <div class="col-sm-6">

        <h5 class="text-uppercase"><strong>Get in touch</strong></h5>

        <%= form_for @message, url: create_message_url do |f| %>
            <fieldset>

              <div id="alert-area">
                <%= notice %>
                <%= @message.errors.full_messages.join(', ') %>
              </div>

              <div class="row">
                <div class="col-sm-6">
                  <p>
                    <%= f.label :name %>
                    <%= f.text_field :name, :class => 'col-xs-12', :id => 'name'  %>
                  </p>
                </div>

                <div class="col-sm-6">
                  <p>
                    <%= f.label :email %>
                    <%= f.email_field :email, :class => 'col-xs-12', :id => 'email' %>
                  </p>
                </div>
              </div>

              <p>
                <%= f.label :subject %>
                <%= f.text_field :subject, :class => 'col-xs-12', :id => 'subject' %>
              </p>

              <p>
                <%= f.label :body %>
                <%= f.text_area :body, :class => 'col-xs-12', :id => 'message' %>
              </p>

              <%= button_tag(type: 'submit', class: "btn btn-default-1 waves") do %>
                Send
              <% end %>
            </fieldset>
        <% end %>

      </div><!-- col -->
      <div class="col-sm-6">

        <h5 class="text-uppercase"><strong>Contact info</strong></h5>

        <br>

        <p>Aenean luctus mi mollis quam feugiat consequat eu sed eros. Cras suscipit eu est sed imperdiet.
          Curabitur ultrices dolor magna, at ven enatis lacus rutrum nec. Quisque elit velit, lacinia sit amet
          tellus at, auctor suscipit metus. Duis congue nibh at tortor ornare, sed commo do ipsum mattis.</p>

        <br>

        <div class="widget widget-contact no-margin-bottom">

          <ul>
            <li>
              <i class="fa fa-map-marker"></i>
              6404 Pleasantdale Rd, Doraville, <br class="visible-lg-block"> GA 30340
            </li>
            <li>
              <i class="fa fa-phone"></i>
              770-613-0234
            </li>
            <li>
              <i class="fa fa-envelope"></i>
              <a href="mailto:coliman@bellsouth.net">coliman@bellsouth.net</a>
            </li>
          </ul>

        </div><!-- widget-contact -->

        <br><br>

        <div class="social-media">

          <a class="pinterest" href="#"><i class="fa fa-pinterest"></i></a>
          <a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a>
          <a class="instagram" href="#"><i class="fa fa-instagram"></i></a>
          <a class="facebook" href="#"><i class="fa fa-facebook"></i></a>
          <a class="twitter" href="#"><i class="fa fa-twitter"></i></a>

        </div><!-- social-media -->

      </div><!-- col -->
    </div><!-- row -->
  </div><!-- container -->

  <br class="hidden-lg hidden-md"><br class="hidden-lg hidden-md">

  <div id="map">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3310.865425429771!2d-84.24812668509539!3d33.91886298064249!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88f5a7377df634d1%3A0x78dd9bd0a2651b90!2s6404+Pleasantdale+Rd%2C+Doraville%2C+GA+30340!5e0!3m2!1sen!2sus!4v1504895517942"  class="map height-400" allowfullscreen></iframe>
  </div>

</div><!-- PAGE CONTENT -->

app/views/sections/about.html.erb
<!-- PAGE CONTENT -->
<div id="page-content">

  <div id="page-header" class="no-margin-bottom">

    <div class="ken-burn" style="background-image:url(<%= asset_path 'backgrounds/page-header-1.jpg' %>);"></div>

    <div class="container">
      <div class="row">
        <div class="col-sm-12">

          <h1>About Us</h1>

          <ol class="breadcrumb">
            <li><a href="#">Home</a></li>
            <li class="active">About Us</li>
          </ol>

        </div><!-- col -->
      </div><!-- row -->
    </div><!-- container -->

  </div><!-- page-header -->

  <div class="container" id="aboutFirstSentence">
    <div class="row">
      <div class="col-sm-12">

        <h2 class="text-center" id="paddingFirstSentence">Coliman Interior Services is one of Atlanta’s up and coming commercial construction companies.</h2>

        <br>

      </div><!-- col -->
    </div><!-- row -->
  </div><!-- container -->

  <div class="hr"></div>

  <br>

  <section class="full-section half-image" id="section-52">

    <div class="half-image-right" style="background-image:url(<%= asset_path 'about/image-1.jpg' %>);">

      <!--<img src="about/image-1.jpg" alt="">-->
      <%= image_tag('about/image-1.jpg', :alt => '') %>

    </div><!-- half-image-left -->

    <div class="full-section-container">

      <div class="container">
        <div class="row">
          <div class="col-md-6 col-lg-5">

            <h2>It is with great pleasure that we seize this opportunity to introduce our company.</h2>

            <!--<h5><em>Duis congue nibh at tortor ornare,-->
              <!--sed commo do ipsum mattis.</em></h5>-->

            <br>

            <p> We specialize in commercial metal framing, sheetrock installation, acoustical ceilings, finishing and in meeting the expectations of our clients.
              We have served some of Atlanta’s best known construction companies with great pride in our work ethic of
              service. Our patrons benefit from our skill of personnel, and the customized attention we offer on each job site.</p>

            <br>

          </div><!-- col -->
        </div><!-- row -->
      </div><!-- container -->

    </div><!-- full-section-container -->
  </section><!-- full-section -->

  <!--<section class="full-section half-image" id="section-53">-->

    <!--<div class="half-image-left" style="background-image:url(<%= asset_path 'about/image-2.jpg' %>);">-->

      <!--&lt;!&ndash;<img src="about/image-2.jpg" alt="">&ndash;&gt;-->
      <!--<%= image_tag('about/image-2.jpg', :alt => '') %>-->

    <!--</div>&lt;!&ndash; half-image-left &ndash;&gt;-->

    <!--<div class="full-section-container">-->

      <!--<div class="container">-->
        <!--<div class="row">-->
          <!--<div class="col-lg-offset-7 col-md-offset-6 col-lg-5 col-md-6">-->

            <!--<h2>Friendly layouts <br class="visible-lg-block"> to suit your needs</h2>-->

            <!--<h5>Duis congue nibh at tortor ornare, sed commo do ipsum mattis.</h5>-->

            <!--<br>-->

            <!--<p>Mollis quam feugiat consequat eu sed eros. Cras suscipit eu est sed imperdiet. Curabitur-->
              <!--ultrices dolor magna, at ven enatis lacus rutrum nec. Quisque elit velit, lacinia sit amet-->
              <!--tellus at, auctor suscipit metus. Duis congue nibh at tortor ornare, sed commo.</p>-->

            <!--<br>-->

          <!--</div>&lt;!&ndash; col &ndash;&gt;-->
        <!--</div>&lt;!&ndash; row &ndash;&gt;-->
      <!--</div>&lt;!&ndash; container &ndash;&gt;-->

    <!--</div>&lt;!&ndash; full-section-container &ndash;&gt;-->
  <!--</section>&lt;!&ndash; full-section &ndash;&gt;-->

  <section class="full-section dark-section parallax" id="section-1" data-stellar-background-ratio="0.1">
    <div class="full-section-container">

      <div class="container">
        <div class="row">
          <div class="col-sm-12 text-center">

            <h6 class="testimonial-title">Happy Clients</h6>

          </div><!-- col -->
        </div><!-- row -->
      </div><!-- container -->

      <div class="container">
        <div class="row">
          <div class="col-sm-12">

            <div class="owl-carousel testimonials-slider">
              <div class="item">

                <div class="testimonial">

                  <blockquote>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit lobortis dolor.
                      Cras placerat lectus a posuere aliquet. Curabitur quis vehicula odio.</p>
                  </blockquote>

                  <h5>John Turner, <span>Constructor</span></h5>

                </div><!-- testimonial -->

              </div><!-- item -->
              <div class="item">

                <div class="testimonial">

                  <blockquote>
                    <p>Nam quis purus sagittis, mattis purus a, pharetra lectus. Ut eget mollis
                      turpis. Cras in rutrum arcu. Cras vel erat elementum sollicitudin.</p>
                  </blockquote>

                  <h5>Mark Smith, <span>Developer</span></h5>

                </div><!-- testimonial -->

              </div><!-- item -->
              <div class="item">

                <div class="testimonial">

                  <blockquote>
                    <p>Maecenas dignissim tempus est. Integer tristique tortor eros, sit amet
                      elementum quam maximus id. In et tristique dui ante magna.</p>
                  </blockquote>

                  <h5>Kate Carter, <span>Designer</span></h5>

                </div><!-- testimonial -->

              </div><!-- item -->
            </div><!-- testimonials-slider -->

          </div><!-- col -->
        </div><!-- row -->
      </div><!-- container -->

    </div><!-- full-section-container -->
  </section><!-- full-section -->

  <div class="container">
    <div class="row">
      <div class="col-sm-12">

        <div class="headline text-center">

          <h2>Company history</h2>

        </div><!-- headline -->

      </div><!-- col -->
    </div><!-- row -->
  </div><!-- container -->

  <div class="container">
    <div class="row">
      <div class="col-sm-12">

        <ul class="vertical-timeline">
          <li class="wow fadeInUp" data-wow-offset="50">

            <h4 class="period">June <br> 2007</h4>

            <div class="period-details">

              <h6>We first started our business</h6>

              <p>Aenean luctus mi mollis quam feugiat consequat eu sed eros. Cras suscipit eu est sed
                imperdiet. Curabitur ultrices dolor magna, at vene natis lacus rutrum nec. Quisque elit
                velit. Aenean luctus mi mollis quam feugiat consequat eu sed eros. Cras suscipit eu est
                sed imperdiet. Curabitur ultrices dolor magna, at vene natis lacus rutrum nec. Quisque
                elit velit.</p>

            </div><!-- period-details -->

          </li>
          <li class="wow fadeInUp" data-wow-offset="50">

            <h4 class="period">January <br> 2009</h4>

            <div class="period-details">

              <h6>Our first major contract</h6>

              <p>Luctus mi mollis quam feugiat consequat eu sed eros. Cras suscipit eu est sed
                imperdiet. Curabitur ultrices dolor magna, at vene natis lacus rutrum nec. Quisque elit
                velit, lacinia. Aenean luctus mi mollis quam feugiat consequat eu sed eros. Cras suscipit
                eu est sed imperdiet. Curabitur ultrices dolor magna, at vene natis lacus rutrum nec.</p>

            </div><!-- period-details -->

          </li>
          <li class="wow fadeInUp" data-wow-offset="50">

            <h4 class="period">August <br> 2011</h4>

            <div class="period-details">

              <h6>The team si growing with 4 new members</h6>

              <p>Mi mollis quam feugiat consequat eu sed eros. Cras suscipit eu est sed imper diet.
                Curabitur ultrices dolor magna, at vene natis lacus rutrum nec. Quisque elit velit,
                lacinia. Aenean luctus mi mollis quam feugiat consequat eu sed eros. Cras suscipit eu est
                sed imperdiet. Curabitur ultrices dolor magna, at vene natis lacus rutrum.</p>

            </div><!-- period-details -->

          </li>
          <li class="wow fadeInUp" data-wow-offset="50">

            <h4 class="period">June <br> 2014</h4>

            <div class="period-details">

              <h6>We invested a big capital</h6>

              <p>Sed ultricies a sem sed porta. In nec quam eu purus lacinia dapibus. Mauris egestas
                tincidunt nisl id finibus. Donec sit amet lobortis leo, nec laoreet nunc. Nam aliquam
                iaculis tristique. In scelerisque pretium quam pretium tempus. Vivamus blandit, purus
                quis lobortis viverra, neque diam laoreet libero, sit amet dapibus felis nisl.</p>

            </div><!-- period-details -->

          </li>
          <li class="wow fadeInUp" data-wow-offset="50">

            <h4 class="period">January <br> 2016</h4>

            <div class="period-details">

              <h6>Our first big award winning</h6>

              <p>Pellentesque euismod ligula sit amet purus iaculis, in elementum tortor mollis.
                Aliquam id facilisis metus. In volutpat, felis nec vehicula ultrices, nulla ipsum
                elementum dui, vel commodo purus quam vel dolor. Aenean tincidunt facilisis accumsan.
                Vivamus lacinia sit amet nisl et egestas.</p>

            </div><!-- period-details -->

          </li>
        </ul>

      </div><!-- col -->
    </div><!-- row -->
  </div><!-- container -->

  <!--<section class="full-section dark-section parallax" id="section-5" data-stellar-background-ratio="0.1">-->
    <!--<div class="full-section-container">-->

      <!--<div class="container">-->
        <!--<div class="row">-->
          <!--<div class="col-sm-12">-->

            <!--<h3 class="text-center">Subscribe to our newsletter to get the latest trends &amp; news</h3>-->
            <!--<h5 class="text-center">Join Us!</h5>-->

          <!--</div>&lt;!&ndash; col &ndash;&gt;-->
        <!--</div>&lt;!&ndash; row &ndash;&gt;-->
      <!--</div>&lt;!&ndash; container &ndash;&gt;-->

      <!--<div class="container">-->
        <!--<div class="row">-->
          <!--<div class="col-sm-12">-->

            <!--<div class="widget widget-newsletter">-->

              <!--<form name="newsletter" novalidate method="post" action="#">-->
                <!--<fieldset>-->
                  <!--<div class="row">-->
                    <!--<div class="col-sm-3">-->

                      <!--<input type="text" name="name" placeholder="Name">-->

                    <!--</div>&lt;!&ndash; col &ndash;&gt;-->
                    <!--<div class="col-sm-6">-->

                      <!--<input type="text" name="email" placeholder="Your e-mail">-->

                    <!--</div>&lt;!&ndash; col &ndash;&gt;-->
                    <!--<div class="col-sm-3">-->

                      <!--<button class="btn btn-grey bordered" type="submit" name="submit" value="">Subscribe <i class="fa fa-angle-right"></i></button>-->

                    <!--</div>&lt;!&ndash; col &ndash;&gt;-->
                  <!--</div>&lt;!&ndash; row &ndash;&gt;-->
                <!--</fieldset>-->
              <!--</form>-->

            <!--</div>&lt;!&ndash; widget-newsletter &ndash;&gt;-->

          <!--</div>&lt;!&ndash; col &ndash;&gt;-->
        <!--</div>&lt;!&ndash; row &ndash;&gt;-->
      <!--</div>&lt;!&ndash; container &ndash;&gt;-->

    <!--</div>&lt;!&ndash; full-section-container &ndash;&gt;-->
  <!--</section>&lt;!&ndash; full-section &ndash;&gt;-->

</div><!-- PAGE CONTENT -->

app/views/sections/contact.html.erb
<!-- PAGE CONTENT -->
<div id="page-content">

  <div id="page-header" class="parallax" data-stellar-background-ratio="0.1" style="background-image:url(<%= asset_path 'backgrounds/page-header-8.jpg' %>);">

    <div class="container">
      <div class="row">
        <div class="col-sm-12">

          <h1>Contact</h1>

          <ol class="breadcrumb">
            <li><a href="#">Home</a></li>
            <li class="active">Contact</li>
          </ol>

        </div><!-- col -->
      </div><!-- row -->
    </div><!-- container -->

  </div><!-- page-header -->

  <div class="container">
    <div class="row">
      <div class="col-sm-6">

        <h5 class="text-uppercase"><strong>Get in touch</strong></h5>

        <form id="contact-form" name="contact-form" method="post" action="assets/php/send.php">
          <fieldset>

            <div id="alert-area"></div>

            <div class="row">
              <div class="col-sm-6">

                <p>
                  <input class="col-xs-12" id="name" type="text" name="name" placeholder="" required>
                  <label for="name">Name</label>
                </p>

              </div><!-- col -->
              <div class="col-sm-6">

                <p>
                  <input class="col-xs-12" id="email" type="text" name="email" placeholder="" required>
                  <label for="email">E-mail</label>
                </p>

              </div><!-- col -->
            </div><!-- row -->

            <p>
              <input class="col-xs-12" id="subject" type="text" name="subject" placeholder="" required>
              <label for="subject">Subject</label>
            </p>

            <p>
              <textarea class="col-xs-12" id="message" name="message" rows="4" cols="25" placeholder="" required></textarea>
              <label for="message">Message</label>
            </p>

            <button class="btn btn-default-1 waves" id="submit" type="submit" name="submit" value="">Send message</button>

          </fieldset>
        </form>

      </div><!-- col -->
      <div class="col-sm-6">

        <h5 class="text-uppercase"><strong>Contact info</strong></h5>

        <br>

        <p>Aenean luctus mi mollis quam feugiat consequat eu sed eros. Cras suscipit eu est sed imperdiet.
          Curabitur ultrices dolor magna, at ven enatis lacus rutrum nec. Quisque elit velit, lacinia sit amet
          tellus at, auctor suscipit metus. Duis congue nibh at tortor ornare, sed commo do ipsum mattis.</p>

        <br>

        <div class="widget widget-contact no-margin-bottom">

          <ul>
            <li>
              <i class="fa fa-map-marker"></i>
              4124 Peachtree Street, Atlanta, <br class="visible-lg-block"> GA 30301
            </li>
            <li>
              <i class="fa fa-phone"></i>
              770-613-0234
            </li>
            <li>
              <i class="fa fa-envelope"></i>
              <a href="mailto:coliman@bellsouth.net">coliman@bellsouth.net</a>
            </li>
          </ul>

        </div><!-- widget-contact -->

        <br><br>

        <div class="social-media">

          <a class="pinterest" href="#"><i class="fa fa-pinterest"></i></a>
          <a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a>
          <a class="instagram" href="#"><i class="fa fa-instagram"></i></a>
          <a class="facebook" href="#"><i class="fa fa-facebook"></i></a>
          <a class="twitter" href="#"><i class="fa fa-twitter"></i></a>

        </div><!-- social-media -->

      </div><!-- col -->
    </div><!-- row -->
  </div><!-- container -->

  <br class="hidden-lg hidden-md"><br class="hidden-lg hidden-md">

  <div class="map no-margin-bottom" data-zoom="15" data-height="565" data-address="6404 Pleasantdale Rd, Doraville, GA, USA">
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC5m9Ayi3jWXe5C6iWCY3WYJKph6V1luxE&amp;callback=initMap" async defer></script>
  </div>

</div><!-- PAGE CONTENT -->